# Generated by Django 3.0.10 on 2020-09-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote4change', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
